version: "3.5"
services:
  centos7php73:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
  centos7php73rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7

networks:
  buildnet:
    external: true
    name: buildnet
