version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.0.0

workflows:
  php74build:
    jobs:
      - docker-rpmbuild/rpmbuild:
          name: centos7php74
          base_service: centos7php74base
          build_service: centos7php74
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: centos7php74rel
          base_service: centos7php74base
          build_service: centos7php74rel
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: centos8php74
          base_service: centos8php74base
          build_file: docker-compose.el8.yml
          build_service: centos8php74
          bintray_uploader: centos8bintray
      - docker-rpmbuild/rpmbuild:
          name: centos8php74rel
          base_service: centos8php74base
          build_file: docker-compose.el8.yml
          build_service: centos8php74rel
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7php74build
          build_service: centos7php74build
          requires:
            - centos7php74
      - docker-rpmbuild/image:
          name: centos7php74buildrel
          build_service: centos7php74buildrel
          requires:
            - centos7php74rel
      - docker-rpmbuild/image:
          name: centos8php74build
          compose_file: build/docker-compose.el8.yml
          build_service: centos8php74build
          requires:
            - centos8php74
      - docker-rpmbuild/image:
          name: centos8php74buildrel
          compose_file: build/docker-compose.el8.yml
          build_service: centos8php74buildrel
          requires:
            - centos8php74rel
      - docker-rpmbuild/image:
          name: centos7php74run
          compose_file: run/docker-compose.yml
          build_service: centos7php74run
          requires:
            - centos7php74
      - docker-rpmbuild/image:
          name: centos7php74devbase
          compose_file: run/docker-compose.yml
          build_service: centos7php74devbase
          requires:
            - centos7php74
      - docker-rpmbuild/image:
          name: centos8php74run
          compose_file: run/docker-compose.el8.yml
          build_service: centos8php74run
          requires:
            - centos8php74
      - docker-rpmbuild/image:
          name: centos8php74devbase
          compose_file: run/docker-compose.el8.yml
          build_service: centos8php74devbase
          requires:
            - centos8php74
      - docker-rpmbuild/image:
          name: centos7php74dev
          compose_file: run/docker-compose.dev.yml
          build_service: centos7php74dev
          requires:
            - centos7php74devbase
      - docker-rpmbuild/image:
          name: centos8php74dev
          compose_file: run/docker-compose.dev.yml
          build_service: centos8php74dev
          requires:
            - centos8php74devbase